### ISSUE TITLE
npm script `deploy` conflicts with `jss deploy` command

### ISSUE THREAD

**Issue by aweber1** [uniformdev/sitecore-jss-nextjs-starterkit#15]
The `deploy` script defined in `package.json` prevents `jss deploy` from running as the JSS CLI gives precedence to commands defined in `package.json`. Therefore, running `jss deploy` in this case is the equivalent of `npm run deploy`.

Theoretically, this seems like something that should be changed in the JSS CLI, but we can work around it by renaming our `deploy` script.

**Comment by alexshyba** [comment]
closing as it is not relevant anymore.
